name: Static Code Analysis

on: [push]

jobs:
  vala-lint:
    name: Vala LINT
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: io.elementary.vala-lint -d .

  pylint:
    name: PyLINT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
